const TourData = [
  {
    id: 1011,
    title: "Historic Tour of Milan with Fast Lane for The Last Supper",
    img: "https://media-cdn.tripadvisor.com/media/attractions-splice-spp-720x480/07/37/c0/0e.jpg",
    description: "Discover the attractions of Milan in a single day of this guided tour, which visits the monastery of Santa Maria delle Grazie, a UNESCO World Heritage Site, which houses the iconic 'Last Supper' by Leonardo Da Vinci, the Castello Sforzesco, the Duomo of Milan and the Galleria Vittorio Emanuele II. With an art historian guide, learn the stories behind the masterpieces and, as the tour is limited to a small group, you get a lot of personal attention.",
    category: "Best Offers",
    rate: "4.5",
    reviews: "502",
    time: "3 hrs",
    price: "83€",
    provider: "tripadvisor",
    linkTo: "https://www.tripadvisor.it/AttractionProductReview-g187849-d12467843-Historic_Milan_Tour_with_Skip_the_Line_Last_Supper_Ticket-Milan_Lombardy.html"
  },
  {
    id: 1012,
    title: "Day Tour in Italy and Switzerland: Lake Como Tour, Bellagio and Lugano from Milan",
    img: "https://media-cdn.tripadvisor.com/media/attractions-splice-spp-720x480/10/3e/85/0d.jpg" ,
    description: "Admire two of the most picturesque lakes in Europe, Como in Italy and Lugano in Switzerland, on a day trip from Milan. Sail on Lake Como, with enough free time to explore the pretty towns along the lake on both sides of the Italian-Swiss border. Travel by bus and ferry along the route instead of stressing driving and sailing. Listen to comments on Como, learning more about the area than you would do alone.",
    category: "Best Offers",
    rate: "4.5",
    reviews: "394",
    time: "10 hrs",
    price: "114€",
    provider: "tripadvisor",
    linkTo: "https://www.tripadvisor.it/AttractionProductReview-g187849-d11449779-Italy_and_Switzerland_Day_Trip_Lake_Como_Bellagio_Lugano_from_Milan-Milan_Lombardy.html"
  },
  {
    id: 1013,
    title: "Mysteries of Milan: discover the lesser-known stories of the city in this audio tour",
    img: "https://media-cdn.tripadvisor.com/media/attractions-splice-spp-720x480/0b/23/18/39.jpg" ,
    description: "In this self-guided audio tour, I’ll show you why Milan has more to offer than design fairs and fashion houses. We will start from the city’s cathedral, which is its most famous landmark, but from there I will help you to look for its lesser known corners. You will meet despots of the Middle Ages, colorful Renaissance characters and the strange saint along the way. Grim Reaper also makes an appearance.",
    category: "Best Offers",
    rate: "4.2",
    reviews: "4",
    time: "1 hr",
    price: "7.50€",
    provider: "tripadvisor",
    linkTo: "https://www.tripadvisor.it/AttractionProductReview-g187849-d21190085-Mysteries_of_Milan_Uncover_the_city_s_lesser_known_tales_on_this_audio_tour-Milan_.html"
  },
  {
    id: 1014,
    title: "Highlights of Milan Self-guided treasure hunt and walking tour",
    img: "https://media-cdn.tripadvisor.com/media/attractions-splice-spp-720x480/0e/aa/7c/46.jpg" ,
    description: "If you’re a fan of puzzles or a treasure hunt lover, take your next mission to the streets of Milan with this self-guided, downloadable tour on your smartphone. You will explore the city, see the sights and have fun while looking for clues, solving puzzles about a route that lasts about two hours. When you play it depends on you; the game offers a flexible way to visit Milan.",
    category: "Best Offers",
    rate: "5",
    reviews: "3",
    time: "2 hrs",
    price: "14€",
    provider: "tripadvisor",
    linkTo: "https://www.tripadvisor.it/AttractionProductReview-g187849-d21137293-Milan_Highlights_Self_guided_scavenger_hunt_and_Walking_Tour-Milan_Lombardy.html"
  },
  {
    id: 1021,
    title: "Private Tour of the Best of Milan: Top Hide Attractions and Treasures with a Local Guide",
    img: "https://media-cdn.tripadvisor.com/media/attractions-splice-spp-720x480/12/8a/06/72.jpg" ,
    description: "",
    category: "City Tours",
    rate: "5",
    reviews: "158",
    time: "3 hrs",
    price: "109€",
    provider: "tripadvisor",
    linkTo: "https://www.tripadvisor.it/AttractionProductReview-g187849-d12650735-Milan_PRIVATE_TOUR_With_Locals_Highlights_Hidden_Gems-Milan_Lombardy.html"
  },
  {
    id: 1022,
    title: "",
    img: "" ,
    description: "",
    category: "City Tours",
    rate: "",
    reviews: "",
    time: "",
    price: "€",
    provider: "tripadvisor",
    linkTo: ""
  },
  {
    id: 1023,
    title: "",
    img: "" ,
    description: "",
    category: "City Tours",
    rate: "",
    reviews: "",
    time: "",
    price: "€",
    provider: "tripadvisor",
    linkTo: ""
  },
  {
    id: 1024,
    title: "",
    img: "" ,
    description: "",
    category: "City Tours",
    rate: "",
    reviews: "",
    time: "",
    price: "€",
    provider: "tripadvisor",
    linkTo: ""
  },
  {
    id: 1031,
    title: "Milan Super Saver: skip the line for the guided tour of the Duomo and the roof",
    img: "https://media-cdn.tripadvisor.com/media/attractions-splice-spp-720x480/07/be/71/01.jpg" ,
    description: "",
    category: "Art & Culture",
    rate: "4.5",
    reviews: "176",
    time: "2.3 hrs",
    price: "70€",
    provider: "tripadvisor",
    linkTo: "https://www.tripadvisor.it/AttractionProductReview-g187849-d11453954-Milan_Super_Saver_Skip_the_Line_Duomo_and_Rooftop_Guided_Tour-Milan_Lombardy.html"
  },
  {
    id: 1032,
    title: "Last Supper and Santa Maria delle Grazie: skip-the-line entrance and guided tour",
    img: "https://media-cdn.tripadvisor.com/media/attractions-splice-spp-720x480/12/45/ab/2f.jpg" ,
    description: "",
    category: "Art & Culture",
    rate: "4.7",
    reviews: "158",
    time: "1.30 hrs",
    price: "79€",
    provider: "tripadvisor",
    linkTo: "https://www.tripadvisor.it/AttractionProductReview-g187849-d25070270-Milan_Last_Supper_and_S_Maria_delle_Grazie_skip_the_line_Tickets_and_Tour-Milan_Lo.html"
  },
  {
    id: 1033,
    title: "Entrance to the Pinacoteca Ambrosia and Leonardo da Vinci’s Codex Atlanticus in Milan",
    img: "https://media-cdn.tripadvisor.com/media/attractions-splice-spp-720x480/07/85/8b/81.jpg" ,
    description: "",
    category: "Art & Culture",
    rate: "4.3",
    reviews: "81",
    time: "2 hrs",
    price: "16€",
    provider: "tripadvisor",
    linkTo: "https://www.tripadvisor.it/AttractionProductReview-g187849-d11995147-Pinacoteca_Ambrosiana_and_da_Vinci_s_Codex_Atlanticus_admission_in_Milan-Milan_Lom.html"
  },
  {
    id: 1034,
    title: "",
    img: "" ,
    description: "",
    category: "Art & Culture",
    rate: "",
    reviews: "",
    time: "",
    price: "€",
    provider: "tripadvisor",
    linkTo: ""
  },
  {
    id: 1041,
    title: "Milan Street Food and Aperitvo Tour - Do Eat Better Experience",
    img: "https://media-cdn.tripadvisor.com/media/attractions-splice-spp-720x480/10/5f/04/33.jpg" ,
    description: "",
    category: "Food",
    rate: "4.8",
    reviews: "230",
    time: "3.5 hrs",
    price: "89€",
    provider: "tripadvisor",
    linkTo: "https://www.tripadvisor.it/AttractionProductReview-g187849-d13973803-Milan_Mix_Aperitivo_Street_Food_Tour-Milan_Lombardy.html"
  },
  {
    id: 1042,
    title: "Best Street Food Walking Tour",
    img: "https://media-cdn.tripadvisor.com/media/attractions-splice-spp-720x480/06/96/71/c1.jpg" ,
    description: "",
    category: "Food",
    rate: "5",
    reviews: "234",
    time: "3 hrs",
    price: "94€",
    provider: "tripadvisor",
    linkTo: "https://www.tripadvisor.it/AttractionProductReview-g187849-d15217446-Best_Street_Food_Walking_Tour_in_Milan-Milan_Lombardy.html"
  },
  {
    id: 1043,
    title: "Gnocchi, pasta, tiramisu and wine lesson",
    img: "https://media-cdn.tripadvisor.com/media/attractions-splice-spp-720x480/11/ab/38/02.jpg" ,
    description: "",
    category: "Food",
    rate: "5",
    reviews: "32",
    time: "3hrs",
    price: "119€",
    provider: "tripadvisor",
    linkTo: "https://www.tripadvisor.it/AttractionProductReview-g187849-d26456185-Gnocchi_Pasta_Tiramisu_and_Wine_Class-Milan_Lombardy.html"
  },
  {
    id: 1044,
    title: "",
    img: "" ,
    description: "",
    category: "Food",
    rate: "",
    reviews: "",
    time: "",
    price: "€",
    provider: "tripadvisor",
    linkTo: ""
  },
  {
    id: 1051,
    title: "Barolo wine tasting, Alba, UNESCO Castle: small group from Milan",
    img: "https://media-cdn.tripadvisor.com/media/attractions-splice-spp-720x480/12/4f/4f/39.jpg" ,
    description: "",
    category: "Wine & Liquors",
    rate: "5",
    reviews: "25",
    time: "10 hrs",
    price: "199€",
    provider: "tripadvisor",
    linkTo: "https://www.tripadvisor.it/AttractionProductReview-g187849-d27159885-Barolo_wine_Tasting_Alba_UNESCO_Castle_Small_Group_from_Milan-Milan_Lombardy.html"
  },
  {
    id: 1052,
    title: "",
    img: "" ,
    description: "",
    category: "Wine & Liquors",
    rate: "",
    reviews: "",
    time: "",
    price: "€",
    provider: "tripadvisor",
    linkTo: ""
  },
  {
    id: 1053,
    title: "",
    img: "" ,
    description: "",
    category: "Wine & Liquors",
    rate: "",
    reviews: "",
    time: "",
    price: "€",
    provider: "tripadvisor",
    linkTo: ""
  },
  {
    id: 1054,
    title: "",
    img: "" ,
    description: "",
    category: "Wine & Liquors",
    rate: "",
    reviews: "",
    time: "",
    price: "€",
    provider: "tripadvisor",
    linkTo: ""
  },
  {
    id: 1061,
    title: "Milan: entrance ticket to the Natural History Museum + Audioguide",
    img: "https://media-cdn.tripadvisor.com/media/attractions-splice-spp-720x480/12/77/dd/d7.jpg" ,
    description: "",
    category: "Nature",
    rate: "/",
    reviews: "/",
    time: "2 hrs",
    price: "14€",
    provider: "tripadvisor",
    linkTo: "https://www.tripadvisor.it/AttractionProductReview-g187849-d27520307-Milan_Natural_History_Museum_Entry_Ticket_Audio_Guide-Milan_Lombardy.html"
  },
  {
    id: 1062,
    title: "Bellagio and Varenna - Small-Group Tour from Milan with Boat Cruise",
    img: "https://media-cdn.tripadvisor.com/media/attractions-splice-spp-720x480/12/45/8b/da.jpg" ,
    description: "",
    category: "Nature",
    rate: "5",
    reviews: "60",
    time: "10 hrs",
    price: "147€",
    provider: "tripadvisor",
    linkTo: "https://www.tripadvisor.it/AttractionProductReview-g187849-d27112306-Bellagio_Varenna_Small_Group_Tour_from_Milan_with_Boat_Cruise-Milan_Lombardy.html"
  },
  {
    id: 1063,
    title: "",
    img: "" ,
    description: "",
    category: "Nature",
    rate: "",
    reviews: "",
    time: "",
    price: "€",
    provider: "tripadvisor",
    linkTo: ""
  },
  {
    id: 1064,
    title: "",
    img: "" ,
    description: "",
    category: "Nature",
    rate: "",
    reviews: "",
    time: "",
    price: "€",
    provider: "tripadvisor",
    linkTo: ""
  },
  {
    id: 1071,
    title: "",
    img: "" ,
    description: "",
    category: "Adrenaline",
    rate: "",
    reviews: "",
    time: "",
    price: "€",
    provider: "tripadvisor",
    linkTo: ""
  },
  {
    id: 1072,
    title: "",
    img: "" ,
    description: "",
    category: "Adrenaline",
    rate: "",
    reviews: "",
    time: "",
    price: "€",
    provider: "tripadvisor",
    linkTo: ""
  },
  {
    id: 1073,
    title: "",
    img: "" ,
    description: "",
    category: "Adrenaline",
    rate: "",
    reviews: "",
    time: "",
    price: "€",
    provider: "tripadvisor",
    linkTo: ""
  },
  {
    id: 1074,
    title: "",
    img: "" ,
    description: "",
    category: "Adrenaline",
    rate: "",
    reviews: "",
    time: "",
    price: "€",
    provider: "tripadvisor",
    linkTo: ""
  },
  {
    id: 2011,
    title: "",
    img: "" ,
    description: "",
    category: "Best Offers",
    rate: "",
    reviews: "",
    time: "",
    price: "€",
    provider: "getyourguide",
    linkTo: ""
  },
  {
    id: 2012,
    title: "",
    img: "" ,
    description: "",
    category: "Best Offers",
    rate: "",
    reviews: "",
    time: "",
    price: "€",
    provider: "getyourguide",
    linkTo: ""
  },
  {
    id: 2013,
    title: "",
    img: "" ,
    description: "",
    category: "Best Offers",
    rate: "",
    reviews: "",
    time: "",
    price: "€",
    provider: "getyourguide",
    linkTo: ""
  },
  {
    id: 2014,
    title: "",
    img: "" ,
    description: "",
    category: "Best Offers",
    rate: "",
    reviews: "",
    time: "",
    price: "€",
    provider: "getyourguide",
    linkTo: ""
  },
  {
    id: 2021,
    title: "",
    img: "" ,
    description: "",
    category: "City Tours",
    rate: "",
    reviews: "",
    time: "",
    price: "€",
    provider: "getyourguide",
    linkTo: ""
  },
  {
    id: 2022,
    title: "",
    img: "" ,
    description: "",
    category: "City Tours",
    rate: "",
    reviews: "",
    time: "",
    price: "€",
    provider: "getyourguide",
    linkTo: ""
  },
  {
    id: 2023,
    title: "",
    img: "" ,
    description: "",
    category: "City Tours",
    rate: "",
    reviews: "",
    time: "",
    price: "€",
    provider: "getyourguide",
    linkTo: ""
  },
  {
    id: 2024,
    title: "",
    img: "" ,
    description: "",
    category: "City Tours",
    rate: "",
    reviews: "",
    time: "",
    price: "€",
    provider: "getyourguide",
    linkTo: ""
  },
  {
    id: 2031,
    title: "",
    img: "" ,
    description: "",
    category: "Art & Culture",
    rate: "",
    reviews: "",
    time: "",
    price: "€",
    provider: "getyourguide",
    linkTo: ""
  },
  {
    id: 2032,
    title: "",
    img: "" ,
    description: "",
    category: "Art & Culture",
    rate: "",
    reviews: "",
    time: "",
    price: "€",
    provider: "getyourguide",
    linkTo: ""
  },
  {
    id: 2033,
    title: "",
    img: "" ,
    description: "",
    category: "Art & Culture",
    rate: "",
    reviews: "",
    time: "",
    price: "€",
    provider: "getyourguide",
    linkTo: ""
  },
  {
    id: 2034,
    title: "",
    img: "" ,
    description: "",
    category: "Art & Culture",
    rate: "",
    reviews: "",
    time: "",
    price: "€",
    provider: "getyourguide",
    linkTo: ""
  },
  {
    id: 2041,
    title: "",
    img: "" ,
    description: "",
    category: "Food",
    rate: "",
    reviews: "",
    time: "",
    price: "€",
    provider: "getyourguide",
    linkTo: ""
  },
  {
    id: 2042,
    title: "",
    img: "" ,
    description: "",
    category: "Food",
    rate: "",
    reviews: "",
    time: "",
    price: "€",
    provider: "getyourguide",
    linkTo: ""
  },
  {
    id: 2043,
    title: "",
    img: "" ,
    description: "",
    category: "Food",
    rate: "",
    reviews: "",
    time: "",
    price: "€",
    provider: "getyourguide",
    linkTo: ""
  },
  {
    id: 2044,
    title: "",
    img: "" ,
    description: "",
    category: "Food",
    rate: "",
    reviews: "",
    time: "",
    price: "€",
    provider: "getyourguide",
    linkTo: ""
  },
  {
    id: 2051,
    title: "",
    img: "" ,
    description: "",
    category: "Wine & Liquors",
    rate: "",
    reviews: "",
    time: "",
    price: "€",
    provider: "getyourguide",
    linkTo: ""
  },
  {
    id: 2052,
    title: "",
    img: "" ,
    description: "",
    category: "Wine & Liquors",
    rate: "",
    reviews: "",
    time: "",
    price: "€",
    provider: "getyourguide",
    linkTo: ""
  },
  {
    id: 2053,
    title: "",
    img: "" ,
    description: "",
    category: "Wine & Liquors",
    rate: "",
    reviews: "",
    time: "",
    price: "€",
    provider: "getyourguide",
    linkTo: ""
  },
  {
    id: 2054,
    title: "",
    img: "" ,
    description: "",
    category: "Wine & Liquors",
    rate: "",
    reviews: "",
    time: "",
    price: "€",
    provider: "getyourguide",
    linkTo: ""
  },
  {
    id: 2061,
    title: "",
    img: "" ,
    description: "",
    category: "Nature",
    rate: "",
    reviews: "",
    time: "",
    price: "€",
    provider: "getyourguide",
    linkTo: ""
  },
  {
    id: 2062,
    title: "",
    img: "" ,
    description: "",
    category: "Nature",
    rate: "",
    reviews: "",
    time: "",
    price: "€",
    provider: "getyourguide",
    linkTo: ""
  },
  {
    id: 2063,
    title: "",
    img: "" ,
    description: "",
    category: "Nature",
    rate: "",
    reviews: "",
    time: "",
    price: "€",
    provider: "getyourguide",
    linkTo: ""
  },
  {
    id: 2064,
    title: "",
    img: "" ,
    description: "",
    category: "Nature",
    rate: "",
    reviews: "",
    time: "",
    price: "€",
    provider: "getyourguide",
    linkTo: ""
  },
  {
    id: 2071,
    title: "",
    img: "" ,
    description: "",
    category: "Adrenaline",
    rate: "",
    reviews: "",
    time: "",
    price: "€",
    provider: "getyourguide",
    linkTo: ""
  },
  {
    id: 2072,
    title: "",
    img: "" ,
    description: "",
    category: "Adrenaline",
    rate: "",
    reviews: "",
    time: "",
    price: "€",
    provider: "getyourguide",
    linkTo: ""
  },
  {
    id: 2073,
    title: "",
    img: "" ,
    description: "",
    category: "Adrenaline",
    rate: "",
    reviews: "",
    time: "",
    price: "€",
    provider: "getyourguide",
    linkTo: ""
  },
  {
    id: 2074,
    title: "",
    img: "" ,
    description: "",
    category: "Adrenaline",
    rate: "",
    reviews: "",
    time: "",
    price: "€",
    provider: "getyourguide",
    linkTo: ""
  },

];

export default TourData;
