const TourData = [
  {
    id: 1011,
    title: "",
    img: "" ,
    description: "",
    category: "Best Offers",
    rate: "",
    reviews: "",
    time: "",
    price: "€",
    provider: "tripadvisor",
    linkTo: ""
  },
  {
    id: 1012,
    title: "",
    img: "" ,
    description: "",
    category: "Best Offers",
    rate: "",
    reviews: "",
    time: "",
    price: "€",
    provider: "tripadvisor",
    linkTo: ""
  },
  {
    id: 1013,
    title: "",
    img: "" ,
    description: "",
    category: "Best Offers",
    rate: "",
    reviews: "",
    time: "",
    price: "€",
    provider: "tripadvisor",
    linkTo: ""
  },
  {
    id: 1014,
    title: "",
    img: "" ,
    description: "",
    category: "Best Offers",
    rate: "",
    reviews: "",
    time: "",
    price: "€",
    provider: "tripadvisor",
    linkTo: ""
  },
  {
    id: 1021,
    title: "",
    img: "" ,
    description: "",
    category: "City Tours",
    rate: "",
    reviews: "",
    time: "",
    price: "€",
    provider: "tripadvisor",
    linkTo: ""
  },
  {
    id: 1022,
    title: "",
    img: "" ,
    description: "",
    category: "City Tours",
    rate: "",
    reviews: "",
    time: "",
    price: "€",
    provider: "tripadvisor",
    linkTo: ""
  },
  {
    id: 1023,
    title: "",
    img: "" ,
    description: "",
    category: "City Tours",
    rate: "",
    reviews: "",
    time: "",
    price: "€",
    provider: "tripadvisor",
    linkTo: ""
  },
  {
    id: 1024,
    title: "",
    img: "" ,
    description: "",
    category: "City Tours",
    rate: "",
    reviews: "",
    time: "",
    price: "€",
    provider: "tripadvisor",
    linkTo: ""
  },
  {
    id: 1031,
    title: "",
    img: "" ,
    description: "",
    category: "Art & Culture",
    rate: "",
    reviews: "",
    time: "",
    price: "€",
    provider: "tripadvisor",
    linkTo: ""
  },
  {
    id: 1032,
    title: "",
    img: "" ,
    description: "",
    category: "Art & Culture",
    rate: "",
    reviews: "",
    time: "",
    price: "€",
    provider: "tripadvisor",
    linkTo: ""
  },
  {
    id: 1033,
    title: "",
    img: "" ,
    description: "",
    category: "Art & Culture",
    rate: "",
    reviews: "",
    time: "",
    price: "€",
    provider: "tripadvisor",
    linkTo: ""
  },
  {
    id: 1034,
    title: "",
    img: "" ,
    description: "",
    category: "Art & Culture",
    rate: "",
    reviews: "",
    time: "",
    price: "€",
    provider: "tripadvisor",
    linkTo: ""
  },
  {
    id: 1041,
    title: "",
    img: "" ,
    description: "",
    category: "Food",
    rate: "",
    reviews: "",
    time: "",
    price: "€",
    provider: "tripadvisor",
    linkTo: ""
  },
  {
    id: 1042,
    title: "",
    img: "" ,
    description: "",
    category: "Food",
    rate: "",
    reviews: "",
    time: "",
    price: "€",
    provider: "tripadvisor",
    linkTo: ""
  },
  {
    id: 1043,
    title: "",
    img: "" ,
    description: "",
    category: "Food",
    rate: "",
    reviews: "",
    time: "",
    price: "€",
    provider: "tripadvisor",
    linkTo: ""
  },
  {
    id: 1044,
    title: "",
    img: "" ,
    description: "",
    category: "Food",
    rate: "",
    reviews: "",
    time: "",
    price: "€",
    provider: "tripadvisor",
    linkTo: ""
  },
  {
    id: 1051,
    title: "",
    img: "" ,
    description: "",
    category: "Wine & Liquors",
    rate: "",
    reviews: "",
    time: "",
    price: "€",
    provider: "tripadvisor",
    linkTo: ""
  },
  {
    id: 1052,
    title: "",
    img: "" ,
    description: "",
    category: "Wine & Liquors",
    rate: "",
    reviews: "",
    time: "",
    price: "€",
    provider: "tripadvisor",
    linkTo: ""
  },
  {
    id: 1053,
    title: "",
    img: "" ,
    description: "",
    category: "Wine & Liquors",
    rate: "",
    reviews: "",
    time: "",
    price: "€",
    provider: "tripadvisor",
    linkTo: ""
  },
  {
    id: 1054,
    title: "",
    img: "" ,
    description: "",
    category: "Wine & Liquors",
    rate: "",
    reviews: "",
    time: "",
    price: "€",
    provider: "tripadvisor",
    linkTo: ""
  },
  {
    id: 1061,
    title: "",
    img: "" ,
    description: "",
    category: "Nature",
    rate: "",
    reviews: "",
    time: "",
    price: "€",
    provider: "tripadvisor",
    linkTo: ""
  },
  {
    id: 1062,
    title: "",
    img: "" ,
    description: "",
    category: "Nature",
    rate: "",
    reviews: "",
    time: "",
    price: "€",
    provider: "tripadvisor",
    linkTo: ""
  },
  {
    id: 1063,
    title: "",
    img: "" ,
    description: "",
    category: "Nature",
    rate: "",
    reviews: "",
    time: "",
    price: "€",
    provider: "tripadvisor",
    linkTo: ""
  },
  {
    id: 1064,
    title: "",
    img: "" ,
    description: "",
    category: "Nature",
    rate: "",
    reviews: "",
    time: "",
    price: "€",
    provider: "tripadvisor",
    linkTo: ""
  },
  {
    id: 1071,
    title: "",
    img: "" ,
    description: "",
    category: "Adrenaline",
    rate: "",
    reviews: "",
    time: "",
    price: "€",
    provider: "tripadvisor",
    linkTo: ""
  },
  {
    id: 1072,
    title: "",
    img: "" ,
    description: "",
    category: "Adrenaline",
    rate: "",
    reviews: "",
    time: "",
    price: "€",
    provider: "tripadvisor",
    linkTo: ""
  },
  {
    id: 1073,
    title: "",
    img: "" ,
    description: "",
    category: "Adrenaline",
    rate: "",
    reviews: "",
    time: "",
    price: "€",
    provider: "tripadvisor",
    linkTo: ""
  },
  {
    id: 1074,
    title: "",
    img: "" ,
    description: "",
    category: "Adrenaline",
    rate: "",
    reviews: "",
    time: "",
    price: "€",
    provider: "tripadvisor",
    linkTo: ""
  },
  {
    id: 2011,
    title: "",
    img: "" ,
    description: "",
    category: "Best Offers",
    rate: "",
    reviews: "",
    time: "",
    price: "€",
    provider: "getyourguide",
    linkTo: ""
  },
  {
    id: 2012,
    title: "",
    img: "" ,
    description: "",
    category: "Best Offers",
    rate: "",
    reviews: "",
    time: "",
    price: "€",
    provider: "getyourguide",
    linkTo: ""
  },
  {
    id: 2013,
    title: "",
    img: "" ,
    description: "",
    category: "Best Offers",
    rate: "",
    reviews: "",
    time: "",
    price: "€",
    provider: "getyourguide",
    linkTo: ""
  },
  {
    id: 2014,
    title: "",
    img: "" ,
    description: "",
    category: "Best Offers",
    rate: "",
    reviews: "",
    time: "",
    price: "€",
    provider: "getyourguide",
    linkTo: ""
  },
  {
    id: 2021,
    title: "",
    img: "" ,
    description: "",
    category: "City Tours",
    rate: "",
    reviews: "",
    time: "",
    price: "€",
    provider: "getyourguide",
    linkTo: ""
  },
  {
    id: 2022,
    title: "",
    img: "" ,
    description: "",
    category: "City Tours",
    rate: "",
    reviews: "",
    time: "",
    price: "€",
    provider: "getyourguide",
    linkTo: ""
  },
  {
    id: 2023,
    title: "",
    img: "" ,
    description: "",
    category: "City Tours",
    rate: "",
    reviews: "",
    time: "",
    price: "€",
    provider: "getyourguide",
    linkTo: ""
  },
  {
    id: 2024,
    title: "",
    img: "" ,
    description: "",
    category: "City Tours",
    rate: "",
    reviews: "",
    time: "",
    price: "€",
    provider: "getyourguide",
    linkTo: ""
  },
  {
    id: 2031,
    title: "",
    img: "" ,
    description: "",
    category: "Art & Culture",
    rate: "",
    reviews: "",
    time: "",
    price: "€",
    provider: "getyourguide",
    linkTo: ""
  },
  {
    id: 2032,
    title: "",
    img: "" ,
    description: "",
    category: "Art & Culture",
    rate: "",
    reviews: "",
    time: "",
    price: "€",
    provider: "getyourguide",
    linkTo: ""
  },
  {
    id: 2033,
    title: "",
    img: "" ,
    description: "",
    category: "Art & Culture",
    rate: "",
    reviews: "",
    time: "",
    price: "€",
    provider: "getyourguide",
    linkTo: ""
  },
  {
    id: 2034,
    title: "",
    img: "" ,
    description: "",
    category: "Art & Culture",
    rate: "",
    reviews: "",
    time: "",
    price: "€",
    provider: "getyourguide",
    linkTo: ""
  },
  {
    id: 2041,
    title: "",
    img: "" ,
    description: "",
    category: "Food",
    rate: "",
    reviews: "",
    time: "",
    price: "€",
    provider: "getyourguide",
    linkTo: ""
  },
  {
    id: 2042,
    title: "",
    img: "" ,
    description: "",
    category: "Food",
    rate: "",
    reviews: "",
    time: "",
    price: "€",
    provider: "getyourguide",
    linkTo: ""
  },
  {
    id: 2043,
    title: "",
    img: "" ,
    description: "",
    category: "Food",
    rate: "",
    reviews: "",
    time: "",
    price: "€",
    provider: "getyourguide",
    linkTo: ""
  },
  {
    id: 2044,
    title: "",
    img: "" ,
    description: "",
    category: "Food",
    rate: "",
    reviews: "",
    time: "",
    price: "€",
    provider: "getyourguide",
    linkTo: ""
  },
  {
    id: 2051,
    title: "",
    img: "" ,
    description: "",
    category: "Wine & Liquors",
    rate: "",
    reviews: "",
    time: "",
    price: "€",
    provider: "getyourguide",
    linkTo: ""
  },
  {
    id: 2052,
    title: "",
    img: "" ,
    description: "",
    category: "Wine & Liquors",
    rate: "",
    reviews: "",
    time: "",
    price: "€",
    provider: "getyourguide",
    linkTo: ""
  },
  {
    id: 2053,
    title: "",
    img: "" ,
    description: "",
    category: "Wine & Liquors",
    rate: "",
    reviews: "",
    time: "",
    price: "€",
    provider: "getyourguide",
    linkTo: ""
  },
  {
    id: 2054,
    title: "",
    img: "" ,
    description: "",
    category: "Wine & Liquors",
    rate: "",
    reviews: "",
    time: "",
    price: "€",
    provider: "getyourguide",
    linkTo: ""
  },
  {
    id: 2061,
    title: "",
    img: "" ,
    description: "",
    category: "Nature",
    rate: "",
    reviews: "",
    time: "",
    price: "€",
    provider: "getyourguide",
    linkTo: ""
  },
  {
    id: 2062,
    title: "",
    img: "" ,
    description: "",
    category: "Nature",
    rate: "",
    reviews: "",
    time: "",
    price: "€",
    provider: "getyourguide",
    linkTo: ""
  },
  {
    id: 2063,
    title: "",
    img: "" ,
    description: "",
    category: "Nature",
    rate: "",
    reviews: "",
    time: "",
    price: "€",
    provider: "getyourguide",
    linkTo: ""
  },
  {
    id: 2064,
    title: "",
    img: "" ,
    description: "",
    category: "Nature",
    rate: "",
    reviews: "",
    time: "",
    price: "€",
    provider: "getyourguide",
    linkTo: ""
  },
  {
    id: 2071,
    title: "",
    img: "" ,
    description: "",
    category: "Adrenaline",
    rate: "",
    reviews: "",
    time: "",
    price: "€",
    provider: "getyourguide",
    linkTo: ""
  },
  {
    id: 2072,
    title: "",
    img: "" ,
    description: "",
    category: "Adrenaline",
    rate: "",
    reviews: "",
    time: "",
    price: "€",
    provider: "getyourguide",
    linkTo: ""
  },
  {
    id: 2073,
    title: "",
    img: "" ,
    description: "",
    category: "Adrenaline",
    rate: "",
    reviews: "",
    time: "",
    price: "€",
    provider: "getyourguide",
    linkTo: ""
  },
  {
    id: 2074,
    title: "",
    img: "" ,
    description: "",
    category: "Adrenaline",
    rate: "",
    reviews: "",
    time: "",
    price: "€",
    provider: "getyourguide",
    linkTo: ""
  },

];

export default TourData;
